version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis:6379
      - DATABASE_URL=postgres://rideuser:ride123@db:5432/rides?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - ENV_FILE=/app/.env
      - FLUTTERWAVE_SECRET_KEY=${FLUTTERWAVE_SECRET_KEY}
      - FLUTTERWAVE_PUBLIC_KEY=${FLUTTERWAVE_PUBLIC_KEY}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./src:/app/src
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s  # Increased to allow for slower startups
    restart: unless-stopped
    networks:
      - backend

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: rideuser
      POSTGRES_PASSWORD: ride123
      POSTGRES_DB: rides
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rideuser -d rides"]
      interval: 5s
      timeout: 10s  # Increased timeout
      retries: 15   # Increased retries
      start_period: 30s
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s  # Increased timeout
      retries: 15   # Increased retries
      start_period: 30s
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend

volumes:
  redis_data:
  postgres_data:
  grafana_data:

networks:
  backend:
    driver: bridge
    