scrape_configs:
  - job_name: 'ride-sharing'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080']
        labels:
          service: 'ride-service'
          
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    metrics_path: '/metrics'
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']